### PR TITLE
Fixed temperature stuck at 125c

### PR DESCRIPTION
**Pull request by aruldd**
According to the [datasheet](http://www.ti.com/lit/ds/symlink/hdc1010.pdf),

> 1. Configure the acquisition parameters in register address 0x02:
> (a) Set the acquisition mode to measure both temperature and humidity by setting Bit[12] to 1.

This was not set earlier resulting in the following bug. Fixed it by setting the value as **0x1000**

### CODE REVIEW

**Comment by closedcube** [comment]
Hello,

How did you acquire RH/T measurements : both at the same time or separately?

As per spec:
"(a) Set the acquisition mode to independently measure temperature or humidity by setting Bit[12] to 0." 
and you can use either use T (0x00) or RH (0x01) pointer to read the respectively measurement.

**Comment by aruldd** [comment]
Yes, the included demo sketch measures both at the same time.

**Comment by closedcube** [comment]
Wow... that's interesting!

What is your Arduino- and sensor boards?

**Comment by aruldd** [comment]
I'm using a HDC1010 breakout board by mouser with Arduino Uno.

**Comment by closedcube** [comment]
Do you mean Texas Instruments HDC1010EVM?

We tested our HDC1010 board with Arduino Uno and no issues found.

**Comment by aruldd** [comment]
Yes, I tested with the Texas EVM. I loaded up the demo sketch with the
necessary connections but the temperature was stuck 125c. So we referred
the datasheet and found that the configuration was not done to measure both
the temperature and Humidity. We fixed the value in .begin function and
everything worked well.

**Pull request closed without merging**
